<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CdliAutogenUsernameTest\Filter\RandomDigitsTest'    => __DIR__ . '/tests/CdliAutogenUsernameTest/Filter/RandomDigitsTest.php',
    'CdliAutogenUsernameTest\Filter\StaticStringTest'    => __DIR__ . '/tests/CdliAutogenUsernameTest/Filter/StaticStringTest.php',
    'CdliAutogenUsernameTest\GeneratorTest'              => __DIR__ . '/tests/CdliAutogenUsernameTest/GeneratorTest.php',
    'CdliAutogenUsernameTest\IntegrationTest'            => __DIR__ . '/tests/CdliAutogenUsernameTest/IntegrationTest.php',
    'CdliAutogenUsername\Module'                         => __DIR__ . '/Module.php',
    'CdliAutogenUsername\Filter\RandomDigits'            => __DIR__ . '/src/CdliAutogenUsername/Filter/RandomDigits.php',
    'CdliAutogenUsername\Filter\StaticString'            => __DIR__ . '/src/CdliAutogenUsername/Filter/StaticString.php',
    'CdliAutogenUsername\Filter\FilterInterface'         => __DIR__ . '/src/CdliAutogenUsername/Filter/FilterInterface.php',
    'CdliAutogenUsername\Filter\AbstractFilter'          => __DIR__ . '/src/CdliAutogenUsername/Filter/AbstractFilter.php',
    'CdliAutogenUsername\DatasourceLoader'               => __DIR__ . '/src/CdliAutogenUsername/DatasourceLoader.php',
    'CdliAutogenUsername\Generator'                      => __DIR__ . '/src/CdliAutogenUsername/Generator.php',
    'CdliAutogenUsername\Datasource\ZfcUser'             => __DIR__ . '/src/CdliAutogenUsername/Datasource/ZfcUser.php',
    'CdliAutogenUsername\Datasource\DatasourceInterface' => __DIR__ . '/src/CdliAutogenUsername/Datasource/DatasourceInterface.php',
    'CdliAutogenUsername\FilterBroker'                   => __DIR__ . '/src/CdliAutogenUsername/FilterBroker.php',
    'CdliAutogenUsername\DatasourceBroker'               => __DIR__ . '/src/CdliAutogenUsername/DatasourceBroker.php',
);